---
# tasks file for ansible-role-dada2-run

- name: Create output directories
  file: path={{ data }}/{{ item }} state=directory mode=0777
  with_items:
    - dada
    - software

- name: Copy scripts to target machine
  copy: src="{{ role_path }}/files/{{ item }}" dest="{{ data }}/dada"
  with_items:
    - submit.sh
    - _submit.sh
    - dada_sample_inference.sh
    - dada_sample_inference.R
    - dada_chimera_taxonomy.sh
    - dada_chimera_taxonomy.R
    - sh_general_release_dynamic_01.12.2017.fasta.gz

- name: Submit jobs to cluster
  command: "sh {{ data }}/dada/submit.sh {{ data }} {{ qname }}"
  args:
    chdir: "{{ data }}/dada"
